### PR TITLE
Fix rebuilding of all virtual modules on any change for webpack 4

### PR DESCRIPTION
**Pull request by non25**
**What's the problem this PR addresses?**

Test lets us know more about virtual modules getting reloaded and rebuilt.

**How did you fix it?**

The problem of reloading and rebuilding every virtual module on any change is not fixed yet.

### CODE REVIEW

**Comment by non25** [comment]
I've managed to make old fix work both on webpack 4 and 5, but I can't understand how to make automated tests work too...
Would like to get some help.

**Comment by non25** [comment]
So previous fix, which consist of populating `compiler.fileTimestamps` Map like this:

```javascript
Object.keys(virtualFiles).forEach((file) => {
  compiler.fileTimestamps.set(file, +virtualFiles[file].stats.mtime);
});
```

still works for Webpack 4 in development mode and fixes rebuilds.

`mode: 'development'` crashes Webpack 3, but fix has no effect on it anyway.

Looks like Webpack 5 doesn't have `compiler.fileTimestamps` and we should look for other options.

I've disabled test for Webpack 3 and 5 until we find a solution.
Fix doesn't affect Webpack 3 and 5.

**Comment by larixer** [comment]
Awesome, many thanks Kirill!

**Comment by larixer** [comment]
Published `webpack-virtual-modules@0.4.1`

**Comment by jquense** [comment]
this change seems to break reloading for any file for webpack 5. I've been testing it locally, and rebuilds of the files still _happen_ but they don't make it to the compilation, e.g. the file after the rebuild is still the old code.

**Comment by non25** [comment]
> this change seems to break reloading for any file for webpack 5. I've been testing it locally, and rebuilds of the files still _happen_ but they don't make it to the compilation, e.g. the file after the rebuild is still the old code.

So if you remove this code
```typescript
const virtualFiles = (compiler as any).inputFileSystem._virtualFiles;
const fts = compiler.fileTimestamps as any;
if (virtualFiles && fts && typeof fts.set === 'function') {
  Object.keys(virtualFiles).forEach((file) => {
    fts.set(file, +virtualFiles[file].stats.mtime);
  });
}
```

it starts to work normally?

Webpack 5 doesn't have `compiler.fileTimestamps`, so condition in this code won't pass. You can try to `console.log` from it to confirm, but I'm quite positive that it shouldn't affect webpack 3 and 5 at all.

**Comment by jquense** [comment]
> Webpack 5 doesn't have compiler.fileTimestamps

I'm not seeing that, it's not _supposed_ to have it but it does exist for back compat: 
image

at least ion 5.1.3. guarding here using `webpack.version` fixed it for me

**Comment by non25** [comment]
Can you make reproduction repo ?
Can't reproduce the problem with webpack 5.3 and webpack 5.10.
https://github.com/non25/webpack-virtual-modules/tree/repro-no-rebuilds

**Pull request merged**
