### PR TITLE
Feat: Support Webpack v5

### PR DESCRIPTION
**Pull request by samcooke98**
**What's the problem this PR addresses?**

I was upgrading [treat](https://github.com/seek-oss/treat), (don't yet have a PR) to support the webpack v5 beta.

It appear that webpack v5 has renamed some of the internal fields used by this plugin. This meant that the virtual modules failed to work in webpack v5.

**How did you fix it?**

I wrote a series of functions that abstract away the webpack internals from theplugin code. Instead of directly accessing `_statBackend ` a function is called that returns the correct "stat backend" depending on the existence. 

Note: I'd love to be able to run tests against both webpack v4 & webpack v5, but I'm not super familiar with mocha \ not sure how that would be possible. 

I tested my changes by manually checking out the code changes `802ee0c43210b32fa8251309485a4e4aa2e2f892` and running `yarn && yarn test` to assert that webpack v4 would continue to be supported.

### CODE REVIEW

**Comment by larixer** [comment]
I'm not sure I can merge Pull Request that contains:
`// TODO: This probably isn't right.`
Plus please make sure that your formatting is in line with formatting used by this plugin code

**Comment by samcooke98** [comment]
> I'm not sure I can merge Pull Request that contains:
> `// TODO: This probably isn't right.`
> Plus please make sure that your formatting is in line with formatting used by this plugin code

Hey, apologies, only just got a chance to come back and fix things up. 

Re; "TODO" - Yep, I was uncertain about the new `levels` stored in webpack-resolve v4. I believe the latest pushed code removes the todo, and mimics webpack's behaviour. However, I'm not entirely sure it's fully correct - I looked at the source code here: https://github.com/webpack/enhanced-resolve/blob/master/lib/CachedInputFileSystem.js#L291 

---

Re; Formatting. Apologies, I'm used to prettier. I've run through it again a bit closer (replaced `if(` with `if (` and `const` -> `var`, as well as a cleaning up all the blank lines I have a bad habit of adding.

**Comment by larixer** [comment]
@samcooke98 Many thanks, looks good now!

**Comment by larixer** [comment]
@samcooke98 Published webpack-virtual-modules@0.3.0

**Pull request merged**
