### PR TITLE
include type definitions in exported files

### PR DESCRIPTION
**Pull request by timse**
This should fix the issue where types are missing in the final package

**What's the problem this PR addresses?**

should address #87

**How did you fix it?**

Add `d.ts` files to exported files of the package

### CODE REVIEW

**Comment by timse** [comment]
On that note - how does this `publishConfig` setting work? It does not get properly replaced when test publishing this package or running `npm pack` or `npm publish --dry-run`.

**Comment by larixer** [comment]
@timse This project uses Yarn package manager, so it should be `yarn pack` instead

**Comment by timse** [comment]
any opinion on the PR @larixer ? :)

**Comment by larixer** [comment]
@timse No opinion yet, have you checked that it actually works, locally?

**Comment by timse** [comment]
I'm having a hard time making this whole pinyarn thing work - not using `publishConfig` and npm works - using `yarn pack` locally works too - so I assume it works.
Its not really a whole lot of magic either - the package.json does not allow `d.ts` files to get published, and that's the only change I made

**Comment by larixer** [comment]
@timse Thank you!

**Comment by larixer** [comment]
Published `webpack-virtual-modules@0.4.2`

**Comment by timse** [comment]
thanks!

**Pull request merged**
